### ISSUE TITLE
Dependency http-parser is unmaintained now

### ISSUE THREAD

**Issue by vikivivi** [FreeRTOS/coreHTTP#102]
Dependency 3rd party module http-parser is unmaintained now, please see https://github.com/nodejs/http-parser/issues/522
Please consider switching or remove dependency.

**Comment by paulbartell** [comment]
@vikivivi : Thanks for the reminder. I will work with the team to determine our path forward.

**Comment by sukhmanm** [comment]
Hi @vikivivi,

Thanks for pointing this out -- we've added a backlog task to investigate this. Since v2.9.3 is included in the NodeJS v12 LTS release, we've reached out to NodeJS regarding the library's LTS support, and are considering the recommended alternative llhttp:  https://github.com/nodejs/node/tree/master/deps/llhttp. Let us know if you have any further questions/comments regarding this. Thanks.
